from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor

def create_report(filepath, title):
    c = canvas.Canvas(filepath, pagesize=letter)
    width, height = letter
    
    # Header Banner
    c.setFillColor(HexColor("#0f172a")) # Dark blue background
    c.rect(0, height - 100, width, 100, fill=1, stroke=0)
    
    # Title
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 24)
    c.drawString(40, height - 55, "LegalOS")
    
    c.setFont("Helvetica", 14)
    c.drawString(40, height - 75, "From Documents to Decisions")
    
    # Document Title
    c.setFillColor(HexColor("#0f172a"))
    c.setFont("Helvetica-Bold", 20)
    c.drawString(40, height - 150, title)
    
    # Separator
    c.setStrokeColor(HexColor("#e2e8f0"))
    c.setLineWidth(2)
    c.line(40, height - 165, width - 40, height - 165)
    
    # Content
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, height - 210, "Case Details:")
    
    c.setFont("Helvetica", 12)
    c.drawString(40, height - 240, "Case ID: CASE-2026-001")
    c.drawString(40, height - 260, "Subject: Cross-Document Intelligence Analysis")
    c.drawString(40, height - 280, "Date Generated: July 12, 2026")
    
    # Summary Box
    c.setFillColor(HexColor("#f8fafc"))
    c.setStrokeColor(HexColor("#cbd5e1"))
    c.rect(40, height - 400, width - 80, 80, fill=1, stroke=1)
    
    c.setFillColor(HexColor("#0f172a"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(55, height - 350, "Executive Summary")
    
    c.setFont("Helvetica", 11)
    c.drawString(55, height - 375, "AI has analyzed 8 documents in this case and identified 1 Critical Mismatch")
    c.drawString(55, height - 390, "regarding the Claim Amount across the Claim Form and Consumer Complaint.")
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(HexColor("#64748b"))
    c.drawString(40, 40, "Generated by LegalOS - Nova Legal LLM Engine (Enterprise Edition)")
    
    c.save()

if __name__ == "__main__":
    import os
    public_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "public")
    
    # Generate the Export bundle
    export_path = os.path.join(public_dir, "LegalOS_Case_Export.pdf")
    create_report(export_path, "Comprehensive Case Export Bundle")
    
    # Generate the Cross-Doc Intel Report
    report_path = os.path.join(public_dir, "Cross_Doc_Intel_Report.pdf")
    create_report(report_path, "Cross-Document Intelligence Report")
    
    print("PDFs generated successfully in the public directory.")
